name: 'reprioritize-issues'
on: 
  issues:
    types: 
      - edited
      - opened

jobs:
  reprioritization-manager:
    permissions: 
      issues: write
      pull-requests: write
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - uses: kaizencc/issue-reprioritization-manager@main
        id: reprioritization-manager
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          original-label: p2
          new-label: p1
          reprioritization-threshold: 1
          project-url: https://github.com/users/kaizencc/projects/1/views/1
      - uses: kaizencc/pr-triage-manager@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          on-pulls: ${{ steps.reprioritization-manager.outputs.linked-pulls }}
